### PR TITLE
Added a Hard-Coded Dark Theme :)

### PR DESCRIPTION
**Pull request by ghost**
Since I do not know much ASM, this will be a bogged and hardcoded fix for #11

### CODE REVIEW

**Comment by fabulousduck** [comment]
fuck i still need to make external files work. i think its better that @rexim works on this one since i only have time on the weekends to work on it.

**Comment by rexim** [comment]
@lorenzoi thanks! I think it's a good stopgap until we have #27 and #26 implemented!

**Comment by rexim** [comment]
@fabulousduck sorry I don't understand how external files related to dark CSS theme. From my point of view they can be implemented independently.

Also, do I understand correctly that you don't have time to work on #18 and I can safely plan it for the streams?

**Comment by fabulousduck** [comment]
@rexim i commented on it since he mentioned he did not know how to write ASM, so external files would be a great help since then he could write normal HTML/CSS in .html files.

And yeah, I simply cant find time for it anymore so you can safely plan it in

**Comment by rexim** [comment]
@fabulousduck got it! Thanks for the explanation.

**Pull request merged**
